//===========================================================================
// Verilog file generated by Clarity Designer    08/05/2020    12:44:46  
// Filename  : csi2_inst_tx_global_operation_bb.v                                                
// IP package: CMOS to D-PHY 1.3                           
// Copyright(c) 2016 Lattice Semiconductor Corporation. All rights reserved. 
//===========================================================================

module csi2_inst_tx_global_operation (

////added ports for handshaking with Rx/bridge or pixel2byte
  input                            clk_hs_en_i,
  input                            d_hs_en_i,
  output                           d_hs_rdy_o,

  // clock and reset
  input wire                       reset_n,
  input wire                       core_clk,
  // interface signals from pkt header and footer
  input wire                       dphy_pkten_i,
  input wire [4*16-1:0] dphy_pkt_i, 
  // interface to DCI wrapper
  // HS i/f
  output wire                      hs_clk_gate_en_o,
  output wire                      hs_clk_en_o,
  output wire                      hs_data_en_o,
  output wire [16-1:0]  hs_data_d1_o,
  output wire [16-1:0]  hs_data_d0_o,
  output wire                      c2d_ready_o,
 
  // LP i/f
  output wire                      lp_clk_en_o,
  output wire                      lp_clk_p_o,
  output wire                      lp_clk_n_o,
  output wire                      lp_data_en_o,
  output wire                      lp_data_p_o,
  output wire                      lp_data_n_o
);

endmodule
