//===========================================================================
// Verilog file generated by Clarity Designer    08/05/2020    12:44:46  
// Filename  : csi2_inst_pixel2byte_bb.v                                                
// IP package: CMOS to D-PHY 1.3                           
// Copyright(c) 2016 Lattice Semiconductor Corporation. All rights reserved. 
//===========================================================================
 
module csi2_inst_pixel2byte (

////added ports for handshaking with LP HS controller
  input                  d_hs_rdy_i, // Flag from LPHS controller that indicates
                                     // it is ready to process data
  output                 d_hs_en_o,  // Flag that indicates request signal from
                                     // from pixel2byte to LPHS controller

  // clock and reset
  input wire                        pix_clk,
  input wire                        core_clk,
  input wire                        reset_n,
  input wire                        pix_rstn, 
    

  input wire                        fv_i,              // frame valid input for CMOS i/f
  input wire                        lv_i,              // line valid input for CMOS i/f
  input wire                        dvalid_i,          // data valid
  input wire [8-1:0]    pixdata_d0_i,

  // DPHY data wiDTh for RGB and RAW
  output wire                       byte_data_en_o,
  output wire [4*16-1:0] byte_data_o,	
  output wire [5:0]                 data_type_o,

  // Frame format for RGB
  output wire                       fv_start_o,
  output wire                       fv_end_o,
  output wire                       lv_start_o,
  output wire                       lv_end_o,
  output wire                       odd_line_o
);

endmodule
