//===========================================================================
// Verilog file generated by Clarity Designer    07/02/2020    13:15:17  
// Filename  : csi2_inst_dci_wrapper.v                                                
// IP package: CMOS to D-PHY 1.3                           
// Copyright(c) 2016 Lattice Semiconductor Corporation. All rights reserved. 
//===========================================================================

module csi2_inst_dci_wrapper (
  // clock and reset
  input wire                      refclk,
  input wire                      reset_n, 
  // MIPI interface signals
  inout wire                      clk_p_o,
  inout wire                      clk_n_o,
  inout wire                      d1_p_o,
  inout wire                      d1_n_o,
  inout wire                      d0_p_io,
  inout wire                      d0_n_io,
  // high-speed transmit signals
  output wire                     txbyte_clkhs_o,
  output wire                     pll_lock_o,
  input wire                      txclk_hsen_i,
  input wire                      txclk_hsgate_i,
  input wire                      pd_dphy_i,
  input wire [16-1:0]  dl1_txdata_hs_i,
  input wire [16-1:0]  dl0_txdata_hs_i,
  input wire                      dl1_txdata_hs_en_i,
  input wire                      dl0_txdata_hs_en_i,
  // low-power transmit signals
  input wire                      txclk_lp_p_i,
  input wire                      txclk_lp_n_i,
  input wire                      clk_lpen_i,
  input wire                      lp_direction_i,
  input wire                      dl1_txdata_lp_p_i,
  input wire                      dl1_txdata_lp_n_i,
  input wire                      dl0_txdata_lp_p_i,
  input wire                      dl0_txdata_lp_n_i,
  input wire                      dl1_txdata_lp_en_i,
  input wire                      dl0_txdata_lp_en_i,
  // Not use - in case to support bus turn-around
  output wire                     rxclk_lp_p_o,
  output wire                     rxclk_lp_n_o,
  output wire                     dl0_rxdata_lp_p_o,
  output wire                     dl0_rxdata_lp_n_o
);

dci_wrapper #(
  .DATA_WIDTH      (16),
  .GEAR_16         (0),
  .CN              (5'd16),
  .CM              (8'd196),
  .CO              (2'd0)
)
dci_wrapper_inst   (
  // clock and reset
  .refclk          (refclk),
  .reset_n         (reset_n), 
  // MIPI interface signals
  .clk_p_o         (clk_p_o),
  .clk_n_o         (clk_n_o),
  .d1_p_o          (d1_p_o),
  .d1_n_o          (d1_n_o),
  .d0_p_io         (d0_p_io),
  .d0_n_io         (d0_n_io),
  // high-speed transmit signals
  .txbyte_clkhs_o  (txbyte_clkhs_o),
  .pll_lock_o      (pll_lock_o),  
  .txclk_hsen_i    (txclk_hsen_i),
  .txclk_hsgate_i  (txclk_hsgate_i),
  .pd_dphy_i       (pd_dphy_i),
  .dl1_txdata_hs_i    (dl1_txdata_hs_i),
  .dl0_txdata_hs_i    (dl0_txdata_hs_i),
  .dl1_txdata_hs_en_i (dl1_txdata_hs_en_i),
  .dl0_txdata_hs_en_i (dl0_txdata_hs_en_i),
  // low-power transmit signals
  .txclk_lp_p_i       (txclk_lp_p_i),
  .txclk_lp_n_i       (txclk_lp_n_i),
  .clk_lpen_i         (clk_lpen_i),
  .lp_direction_i     (lp_direction_i),
  .dl1_txdata_lp_p_i  (dl1_txdata_lp_p_i),
  .dl1_txdata_lp_n_i  (dl1_txdata_lp_n_i),
  .dl0_txdata_lp_p_i  (dl0_txdata_lp_p_i),
  .dl0_txdata_lp_n_i  (dl0_txdata_lp_n_i),
  .dl1_txdata_lp_en_i (dl1_txdata_lp_en_i),
  .dl0_txdata_lp_en_i (dl0_txdata_lp_en_i),
  // Not use - in case to support bus turn-around
  .rxclk_lp_p_o       (rxclk_lp_p_o ),
  .rxclk_lp_n_o       (rxclk_lp_n_o),
  .dl0_rxdata_lp_p_o  (dl0_rxdata_lp_p_o),
  .dl0_rxdata_lp_n_o  (dl0_rxdata_lp_n_o)
);
endmodule
