//===========================================================================
// Verilog file generated by Clarity Designer    07/02/2020    13:15:17  
// Filename  : csi2_inst_inst.v                                                
// IP package: CMOS to D-PHY 1.3                           
// Copyright(c) 2016 Lattice Semiconductor Corporation. All rights reserved. 
//===========================================================================

csi2_inst csi2_inst_inst (
  .pix_clk_i        (pix_clk_i),        // pixel or refclk clock
  .reset_n_i        (reset_n_i),        // (active low) asynchronous reset
  .pd_dphy_i        (pd_dphy_i),        // DPHY PD signal
  .tinit_done_o     (tinit_done_o),     // Tinit done  
  .pll_lock_o       (pll_lock_o),       // PLL clock lock signal
  .fv_i             (fv_i),             // frame valid input for CMOS i/f
  .lv_i             (lv_i),             // line valid input for CMOS i/f
  .dvalid_i         (dvalid_i),         // data valid
  .pixdata_d0_i     (pixdata_d0_i),     // pixel data for CMOS interface
  .d0_p_io          (d0_p_io),          // DPHY output data 0
  .d0_n_io          (d0_n_io),          // DPHY output data 0
  .d1_p_o           (d1_p_o),           // DPHY output data 1
  .d1_n_o           (d1_n_o),           // DPHY output data 1
  .clk_p_o          (clk_p_o),          // DPHY output clock
  .clk_n_o          (clk_n_o)           // DPHY output clock
);

