//===========================================================================
// Verilog file generated by Clarity Designer    08/05/2020    12:44:46  
// Filename  : csi2_inst_dcs_control_bb.v                                                
// IP package: CMOS to D-PHY 1.3                           
// Copyright(c) 2016 Lattice Semiconductor Corporation. All rights reserved. 
//===========================================================================
	
module csi2_inst_dcs_control (
  input wire       clk,
  input	wire       reset_n,
  input	wire       start_i,    // Inititate an 8-bit data transfer
  input	wire       escape_i,   // Initiate a LP11,LP10,LP00,LP01,LP00 transmission
  input	wire       stop_i,
  input wire [7:0] data_i,
  input	wire       rom_done_i,
  output wire      ready_o,
  output wire      done_o,
  output wire      lp_o,
  output wire      ln_o
);

endmodule		

