//===========================================================================
// Verilog file generated by Clarity Designer    08/05/2020    12:44:46  
// Filename  : csi2_inst_tinit_count.v                                                
// IP package: CMOS to D-PHY 1.3                           
// Copyright(c) 2016 Lattice Semiconductor Corporation. All rights reserved. 
//===========================================================================

module csi2_inst_tinit_count (
  input wire    clk	,
  input wire    resetn	,
  output wire   tinit_done_o
);

tinit_count #(
  .TINIT_VALUE  (1000)
)
tinit_count_inst(
  .clk          (clk),
  .resetn       (resetn),
  .tinit_done_o (tinit_done_o)
);

endmodule

