//===========================================================================
// Verilog file generated by Clarity Designer    07/02/2020    13:15:17  
// Filename  : csi2_inst_DCS_hs.v                                                
// IP package: CMOS to D-PHY 1.3                           
// Copyright(c) 2016 Lattice Semiconductor Corporation. All rights reserved. 
//===========================================================================
`timescale 1ns/1ps

module csi2_inst_DCS_hs 
(
////added ports for handshaking with LP HS controller
    input                          d_hs_rdy_i,
    output                         d_hs_en_o,

    input                          reset_n,
    input                          clk,
    input      [16:0]       q_hs_data_d, //{trail ind, data}
    output     [10-1:0]  hs_cmd_cnt,
    output                         hs_en  ,
    output     [16-1:0]     q_hs_data /*synthesis syn_ramstyle = "EBR"*/,
    output                         hs_dcs_done
);

DCS_hs 
  #(
    // Parameters
    .TX_GEAR		(8),   
    .DAT_WIDTH		(16),
    .CMDCNT_WIDTH       (10), 
    .DLY		(1000), //delay between DCS packets
    .TINIT_VALUE        (1000),
    .TX_FREQ_TGT        (111),
    .WORD_CNT           (100))
  DCS_hs_inst
     (
      .d_hs_rdy_i       (d_hs_rdy_i),
      .d_hs_en_o        (d_hs_en_o),
      .reset_n          (reset_n),
      .clk              (clk),
      .q_hs_data_d      (q_hs_data_d),
      .hs_cmd_cnt       (hs_cmd_cnt),
      .hs_en            (hs_en),
      .q_hs_data        (q_hs_data),
      .hs_dcs_done      (hs_dcs_done));
  
endmodule                         
