//===========================================================================
// Verilog module generated by IPexpress    07/02/2020    13:15:17       
// Filename: csi2_inst_params.v                                      
// Copyright(c) 2016 Lattice Semiconductor Corporation. All rights reserved. 
//===========================================================================
`define   TX_CSI2
`define   RGB888
`define   NUM_TX_LANE_2
`define   LP_2
`define   TX_GEAR_8
`define   VC 0
`define   WC 3840
`define   CM 8'd196
`define   CN 5'd16
`define   CO 2'd0
`define   TX_FREQ_TGT 111.3750
`define   ROM_WAIT_TIME 1000
`define   TINIT_VALUE 1000
`define   NUM_PIX_LANE_1
`define   PIX_DPHY
`define   HS_DCS
`define   ESC_SEQ 32'b1111_1111_1111_1111_1111_1111_1000_0100
`define   MISC_ON
`define   BYPASS_DCS
`define   TX_CLK_MODE_HS_ONLY
