//===========================================================================
// Verilog file generated by Clarity Designer    08/05/2020    12:44:46  
// Filename  : csi2_inst_pkt_formatter_bb.v                                                
// IP package: CMOS to D-PHY 1.3                           
// Copyright(c) 2016 Lattice Semiconductor Corporation. All rights reserved. 
//===========================================================================

module csi2_inst_pkt_formatter (
//-----------------------------------
// Added for HS Blanking Support
    input        hsblp_en_i,
    input        hsblp_loop_en_i,
    input [15:0] wc_hsa_i,
    input [15:0] wc_hfp_i,
    input [15:0] wc_hbp_i,
    input [15:0] hfp_chksum_i,
    input [15:0] hbp_chksum_i,
//-----------------------------------
    // clock and reset
    input wire                        reset_n,
    input wire                        core_clk,
    // packet settings
    input wire [1:0]                  vc_i,
    input wire [5:0]                  dt_i,
    input wire [15:0]                 wc_i,
    input wire                        eotp_i,
    // control/data from pixel2byte
    input wire                        fv_start_i,
    input wire                        fv_end_i,
    input wire                        lv_start_i,
    input wire                        lv_end_i,
    input wire [4*16-1:0]  byte_data_i,
    input wire                        byte_data_en_i,
    output wire                       pix2byte_rstn_o,
    output wire [4*16-1:0] dphy_pkt_o,
    output wire                       dphy_pkten_o
);

endmodule

