//===========================================================================
// Verilog file generated by Clarity Designer    07/02/2020    13:15:17  
// Filename  : csi2_inst_tinit_count_bb.v                                                
// IP package: CMOS to D-PHY 1.3                           
// Copyright(c) 2016 Lattice Semiconductor Corporation. All rights reserved. 
//===========================================================================

module csi2_inst_tinit_count (
  input wire    clk	,
  input wire    resetn	,
  output wire   tinit_done_o
);

endmodule

