//===========================================================================
// Verilog file generated by Clarity Designer    08/05/2020    12:44:46  
// Filename  : csi2_inst_synchronizer.v                                                
// IP package: CMOS to D-PHY 1.3                           
// Copyright(c) 2016 Lattice Semiconductor Corporation. All rights reserved. 
//===========================================================================

module csi2_inst_synchronizer (
    input		clk,
    input		rstn,
    input		in,

    output		out
);

reg [1:0]	sync_ff_r;
always @(posedge clk or negedge rstn)
   if (!rstn) begin
      sync_ff_r 	<= 0;
   end
   else begin
      sync_ff_r[0] 	<= in;
      sync_ff_r[1] 	<= sync_ff_r[0];
   end

assign out = sync_ff_r[1];

endmodule
