//===========================================================================
// Verilog file generated by Clarity Designer    08/05/2020    12:44:46  
// Filename  : csi2_inst_sig_delay.v                                                
// IP package: CMOS to D-PHY 1.3                           
// Copyright(c) 2016 Lattice Semiconductor Corporation. All rights reserved. 
//===========================================================================

module csi2_inst_sig_delay (
  input wire   clk,
  input wire   rstn,
  input wire   in, 
  output wire  out
);

sig_delay sig_delay_inst(
  .clk      (clk),
  .rstn     (rstn),
  .in       (in),
  .out      (out)
);

endmodule
