//===========================================================================
// Verilog file generated by Clarity Designer    07/02/2020    13:15:17  
// Filename  : csi2_inst_dcs_control.v                                                
// IP package: CMOS to D-PHY 1.3                           
// Copyright(c) 2016 Lattice Semiconductor Corporation. All rights reserved. 
//===========================================================================
	
module csi2_inst_dcs_control (
  input wire       clk,
  input	wire       reset_n,
  input	wire       start_i,    // Inititate an 8-bit data transfer
  input	wire       escape_i,   // Initiate a LP11,LP10,LP00,LP01,LP00 transmission
  input	wire       stop_i,
  input wire [7:0] data_i,
  input	wire       rom_done_i,
  output wire      ready_o,
  output wire      done_o,
  output wire      lp_o,
  output wire      ln_o
);

dcs_control dcs_control_inst(
  .clk          (clk),
  .reset_n      (reset_n),
  .start_i      (start_i),
  .escape_i     (escape_i),
  .stop_i       (stop_i),
  .data_i       (data_i),
  .rom_done_i   (rom_done_i),
  .ready_o      (ready_o),
  .done_o       (done_o),
  .lp_o         (lp_o),
  .ln_o         (ln_o)
);

endmodule		

