//===========================================================================
// Verilog file generated by Clarity Designer    08/05/2020    12:44:46  
// Filename  : csi2_inst_pkt_header_csi2_2bg.v                                                
// IP package: CMOS to D-PHY 1.3                           
// Copyright(c) 2016 Lattice Semiconductor Corporation. All rights reserved. 
//===========================================================================

module csi2_inst_pkt_header_csi2_2bg (
  // clock and reset
  input wire                        core_rstn,
  input wire                        core_clk_i, 
  // packet settings
  input wire [1:0]                  vc_i,
  input wire [5:0]                  dt_i,
  input wire [15:0]                 wc_i,
  input wire                        gear16_i, 
  // control/data from pixel2byte
  input wire                        sp_req_i,  
  input                             lp_req_i,

  //input from packet_header
  input		                    d_hs_rdy_i,
  input wire [4*16-1:0]  byte_data_i,
  input wire                        byte_data_en_i, 

  output wire                       ld_pyld_o,
  output wire                       pix2byte_rstn_o,
  output wire                       phdr_xfr_done,
  output wire [4*16-1:0] dphy_pkt_o,
  output wire                       dphy_pkten_o
);

pkt_header_csi2_2bg #(
  .LANE_WIDTH    (2),
  .DATA_WIDTH    (16),
  .GEAR_16       (0),
  .CRC16         (1)
)
pkt_header_csi2_2bg_inst (
  .core_rstn       (core_rstn),
  .core_clk_i      (core_clk_i),
  .vc_i            (vc_i),
  .dt_i            (dt_i),
  .wc_i            (wc_i),    
  .gear16_i        (gear16_i),
  .sp_req_i        (sp_req_i), 
  .lp_req_i        (lp_req_i), 
  .d_hs_rdy_i      (d_hs_rdy_i),
  .byte_data_i     (byte_data_i),
  .byte_data_en_i  (byte_data_en_i),
  .ld_pyld_o       (ld_pyld_o),
  .pix2byte_rstn_o (pix2byte_rstn_o),
  .phdr_xfr_done   (phdr_xfr_done),
  .dphy_pkt_o      (dphy_pkt_o),
  .dphy_pkten_o    (dphy_pkten_o)
);

endmodule
